server:
  version: v0.1.1
  addr: :8080
  mode: debug
  static_dir: ./public
  view_dir: ./view
  log_dir: ./log
  upload_dir: ./storage
  cache: ./cache
  max_multipart_memory: 10
  key_scure: secret-key-string

database:
  dialect: mysql
  datasource: root:pass@tcp(localhost:3308)/octvienna?charset=utf8mb4&timeout=10s&parseTime=True
  dir: sql
  table: migrations
  max_idle_conns: 2
  max_open_conns: 16
